-- Add team management related columns
ALTER TABLE teams 
ADD COLUMN deleted_at TIMESTAMP,
ADD COLUMN deleted_by_id BIGINT;

ALTER TABLE projects 
ADD COLUMN deleted_at TIMESTAMP,
ADD COLUMN deleted_by_id BIGINT;

-- Add team member removal tracking
CREATE TABLE team_member_removals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    removed_by_id BIGINT NOT NULL,
    removal_type VARCHAR(50) NOT NULL CHECK (removal_type IN ('KICKED', 'LEFT')),
    removal_reason TEXT,
    removed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    contributions_removed BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (team_id) REFERENCES teams(id),
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (removed_by_id) REFERENCES users(id)
);

-- Add foreign key constraints for deletion tracking
ALTER TABLE teams 
ADD CONSTRAINT FK_teams_deleted_by 
FOREIGN KEY (deleted_by_id) REFERENCES users(id);

ALTER TABLE projects 
ADD CONSTRAINT FK_projects_deleted_by 
FOREIGN KEY (deleted_by_id) REFERENCES users(id);

-- Add indexes for better performance
CREATE INDEX idx_teams_deleted_at ON teams(deleted_at);
CREATE INDEX idx_projects_deleted_at ON projects(deleted_at);
CREATE INDEX idx_team_member_removals_team_user ON team_member_removals(team_id, user_id);
CREATE INDEX idx_team_member_removals_removed_at ON team_member_removals(removed_at);
