name: Security Scan (Disabled)
on:
  # Temporarily disabled due to permissions issues
  # schedule:
  #   - cron: '0 0 * * 1' # Weekly on Mondays
  workflow_dispatch: # Manual trigger only

jobs:
  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Run OWASP Dependency Check
      run: |
        mvn clean compile
        mvn org.owasp:dependency-check-maven:check \
          -DfailBuildOnCVSS=9 \
          -DsuppressionsFile=owasp-suppressions.xml \
          -DskipProvidedScope=true \
          -DskipRuntimeScope=true \
          -DskipTestScope=true
      continue-on-error: true
          
    - name: Upload OWASP report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: owasp-dependency-check-report
        path: target/dependency-check-report.html
        if-no-files-found: ignore
        
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'
        exit-code: '0'
        
    - name: Check if Trivy results exist
      id: check-trivy
      run: |
        if [ -f "trivy-results.sarif" ]; then
          echo "trivy-file-exists=true" >> $GITHUB_OUTPUT
        else
          echo "trivy-file-exists=false" >> $GITHUB_OUTPUT
          echo "Trivy SARIF file not generated, creating empty placeholder"
          echo '{"version": "2.1.0", "runs": []}' > trivy-results.sarif
        fi
        
    - name: Upload Trivy scan results
      uses: github/codeql-action/upload-sarif@v3
      if: always() && steps.check-trivy.outputs.trivy-file-exists == 'true'
      with:
        sarif_file: 'trivy-results.sarif'
        
    - name: CodeQL Analysis
      uses: github/codeql-action/init@v3
      with:
        languages: java
        
    - name: Autobuild
      uses: github/codeql-action/autobuild@v3
      continue-on-error: true
      
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      continue-on-error: true
